### ISSUE TITLE
[enhancement] refactor-pages-to-page-bundles.bash

### ISSUE THREAD

**Issue by NGenetzky** [sourcethemes/academic-scripts#1]
> @NGenetzky please can you consider adding your Bash page bundle script to the new https://github.com/sourcethemes/academic-scripts repo or giving us your approval so we can add it there? I think it will be useful to other users :) Thanks!

[source](https://github.com/NGenetzky/hugo-academic-kickstart/pull/8#issuecomment-435594853)

**Comment by NGenetzky** [comment]
Is there a plan to use subdirectories to categorize the scripts? If so what subdirectory do you think would be best for this script?

**Comment by gcushen** [comment]
You're welcome to suggest a folder name. There's no concrete plan at the moment for how we structure this. Depends how many scripts we end up with. Could have a folder named after the version when the feature first became available, but then users on other versions might not notice that the script exists... Perhaps no folder is best for now so everyone notices it, and in future we can consider moving it if we end up with lots more scripts...

If you are submitting a PR, please can you shorten the name to just `.sh`? The file extension is pretty redundant, but I guess it's nice to have a rough indication what's inside :)

**Comment by gcushen** [comment]
@NGenetzky so are you happy to submit your page bundle script as a PR in this repo?

**Comment by NGenetzky** [comment]
Yes, I just hadn't had a chance to do it yet.

I have to do a little refactoring since by requesting `.sh` extension that also implies that the script shouldn't use bashisms, which it currently does. I will see if I can get one put up today.

**Comment by gcushen** [comment]
Sounds good :)

You misunderstood my point though. The script should **remain a Bash script**, I was just asking to **shorten the extension** as the filename is already very long. The bash environment is set in the shebang (first line of the file) so the file extension can be anything.
