### ISSUE TITLE
Typo/error in code refactor_pages_convert_TOML_to_YAML.py

### ISSUE THREAD

**Issue by bienflorencia** [sourcethemes/academic-scripts#10]
There is an 'f' in the code at line 36 that shouldn't be there.

https://github.com/wowchemy/awesome-hugo/blob/8b2c98203de750a3e7753b0d04558130cee2f0b3/refactor_pages_convert_TOML_to_YAML.py#L36

**Comment by gcushen** [comment]
Closing due to no recent responses from the community.
