### ISSUE TITLE
Illegal option mv --no-target-directory

### ISSUE THREAD

**Issue by sbibauw** [sourcethemes/academic-scripts#4]
No sure if it is because of differences between Linux and macOS, but on my macOS Terminal, running `refactor-pages-to-page-bundles.sh` causes an error:

    mv: illegal option -- h
    usage: mv [-f | -i | -n] [-v] source target
           mv [-f | -i | -n] [-v] source ... directory

I had to remove the `--no-target-directory` after `mv` in the script to be able to run it (worked adequately).

**Comment by gcushen** [comment]
Thanks for reporting this @sbibauw .

A work around is to install the Linux equivalent of mv on Mac (GNU mv via brew) and alias it.

It would be nice to make this script compatible with Mac by default though, so I'll remove `--no-target-directory` in a minute. It appears to be there to catch the case where there is an existing directory named `index.md`, but that edge case should never be reached, so it should be safe to remove it as you discovered.
